//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GtelAccountRequestSoap", Namespace="http://tempuri.org/")]
public partial class GtelAccountRequest : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback registerAccountGTElOperationCompleted;
    
    /// <remarks/>
    public GtelAccountRequest() {
        this.Url = System.Configuration.ConfigurationManager.AppSettings["GTEL_ACCOUNT_REQUEST_WS.URL"]; //"http://sandbox3.vtcebank.vn/VTCAPIService/GtelAccountRequest.asmx";
    }
    
    /// <remarks/>
    public event registerAccountGTElCompletedEventHandler registerAccountGTElCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registerAccountGTEl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string registerAccountGTEl(string msisdn, int active, string Extrafield) {
        object[] results = this.Invoke("registerAccountGTEl", new object[] {
                    msisdn,
                    active,
                    Extrafield});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginregisterAccountGTEl(string msisdn, int active, string Extrafield, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("registerAccountGTEl", new object[] {
                    msisdn,
                    active,
                    Extrafield}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndregisterAccountGTEl(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void registerAccountGTElAsync(string msisdn, int active, string Extrafield) {
        this.registerAccountGTElAsync(msisdn, active, Extrafield, null);
    }
    
    /// <remarks/>
    public void registerAccountGTElAsync(string msisdn, int active, string Extrafield, object userState) {
        if ((this.registerAccountGTElOperationCompleted == null)) {
            this.registerAccountGTElOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregisterAccountGTElOperationCompleted);
        }
        this.InvokeAsync("registerAccountGTEl", new object[] {
                    msisdn,
                    active,
                    Extrafield}, this.registerAccountGTElOperationCompleted, userState);
    }
    
    private void OnregisterAccountGTElOperationCompleted(object arg) {
        if ((this.registerAccountGTElCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.registerAccountGTElCompleted(this, new registerAccountGTElCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void registerAccountGTElCompletedEventHandler(object sender, registerAccountGTElCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class registerAccountGTElCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal registerAccountGTElCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
