//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.17929.
// 
namespace PayWallet.Utils.Service
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SendSMSPublicSoap", Namespace = "http://tempuri.org/")]
    public partial class SendSMSPublic : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;

        /// <remarks/>
        public SendSMSPublic()
        {

            this.Url = System.Configuration.ConfigurationManager.AppSettings["SMS_Public_WS.URL"];
                //"http://localhost:46946/WSSendSMS/SendSMSPublic.asmx"
        }

        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSMS",
            RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/",
            Use = System.Web.Services.Description.SoapBindingUse.Literal,
            ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS(string _Gateway, string _UserID, string _Message, string _Sign)
        {
            object[] results = this.Invoke("SendSMS", new object[]
            {
                _Gateway,
                _UserID,
                _Message,
                _Sign
            });
            return ((string) (results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendSMS(string _Gateway, string _UserID, string _Message, string _Sign,
            System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SendSMS", new object[]
            {
                _Gateway,
                _UserID,
                _Message,
                _Sign
            }, callback, asyncState);
        }

        /// <remarks/>
        public string EndSendSMS(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string) (results[0]));
        }

        /// <remarks/>
        public void SendSMSAsync(string _Gateway, string _UserID, string _Message, string _Sign)
        {
            this.SendSMSAsync(_Gateway, _UserID, _Message, _Sign, null);
        }

        /// <remarks/>
        public void SendSMSAsync(string _Gateway, string _UserID, string _Message, string _Sign, object userState)
        {
            if ((this.SendSMSOperationCompleted == null))
            {
                this.SendSMSOperationCompleted =
                    new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[]
            {
                _Gateway,
                _UserID,
                _Message,
                _Sign
            }, this.SendSMSOperationCompleted, userState);
        }

        private void OnSendSMSOperationCompleted(object arg)
        {
            if ((this.SendSMSCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs =
                    ((System.Web.Services.Protocols.InvokeCompletedEventArgs) (arg));
                this.SendSMSCompleted(this,
                    new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled,
                        invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled,
            object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string) (this.results[0]));
            }
        }
    }
}