//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "UltilServicesSoap", Namespace = "http://tempuri.org/")]
public partial class UltilServices : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback FunctionServicesOperationCompleted;

    /// <remarks/>
    public UltilServices()
    {
        this.Url = System.Configuration.ConfigurationManager.AppSettings["SMS_Service_WS.URL"];
        //this.Url = "http://117.103.207.30:8088/UltilServicesAPI/UltilServices.asmx";
    }

    /// <remarks/>
    public event FunctionServicesCompletedEventHandler FunctionServicesCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FunctionServices", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string FunctionServices(string FromSystem, string FunctionName, string jSonData, string Sign)
    {
        object[] results = this.Invoke("FunctionServices", new object[] {
                    FromSystem,
                    FunctionName,
                    jSonData,
                    Sign});
        return ((string)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginFunctionServices(string FromSystem, string FunctionName, string jSonData, string Sign, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("FunctionServices", new object[] {
                    FromSystem,
                    FunctionName,
                    jSonData,
                    Sign}, callback, asyncState);
    }

    /// <remarks/>
    public string EndFunctionServices(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }

    /// <remarks/>
    public void FunctionServicesAsync(string FromSystem, string FunctionName, string jSonData, string Sign)
    {
        this.FunctionServicesAsync(FromSystem, FunctionName, jSonData, Sign, null);
    }

    /// <remarks/>
    public void FunctionServicesAsync(string FromSystem, string FunctionName, string jSonData, string Sign, object userState)
    {
        if ((this.FunctionServicesOperationCompleted == null))
        {
            this.FunctionServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFunctionServicesOperationCompleted);
        }
        this.InvokeAsync("FunctionServices", new object[] {
                    FromSystem,
                    FunctionName,
                    jSonData,
                    Sign}, this.FunctionServicesOperationCompleted, userState);
    }

    private void OnFunctionServicesOperationCompleted(object arg)
    {
        if ((this.FunctionServicesCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FunctionServicesCompleted(this, new FunctionServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void FunctionServicesCompletedEventHandler(object sender, FunctionServicesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FunctionServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal FunctionServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
