//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Paygate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ButtonOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Paygate.ButtonOrder", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Paygate người nhận không tồn tại. Bạn vui lòng kiểm tra lại dữ liệu.
        /// </summary>
        internal static string AccSalerNotExits {
            get {
                return ResourceManager.GetString("AccSalerNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thẻ.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví dựng thẻ.
        /// </summary>
        internal static string BankCardWallet {
            get {
                return ResourceManager.GetString("BankCardWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanh toán.
        /// </summary>
        internal static string btnConfirm {
            get {
                return ResourceManager.GetString("btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nút thanh toán không tồn tại.
        /// </summary>
        internal static string ButtonNotExits {
            get {
                return ResourceManager.GetString("ButtonNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string BuyerEmail {
            get {
                return ResourceManager.GetString("BuyerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người mua.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số di động.
        /// </summary>
        internal static string BuyerPhone {
            get {
                return ResourceManager.GetString("BuyerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn kiểm tra lại user hoặc pasword.
        /// </summary>
        internal static string CheckUserOrPass {
            get {
                return ResourceManager.GetString("CheckUserOrPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền lên không hợp lệ. Bạn vui lòng kiểm tra lại.
        /// </summary>
        internal static string DataTransferInvalid {
            get {
                return ResourceManager.GetString("DataTransferInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhận hàng.
        /// </summary>
        internal static string DeliveryAddresss {
            get {
                return ResourceManager.GetString("DeliveryAddresss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyên góp.
        /// </summary>
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người quyên góp.
        /// </summary>
        internal static string DonationInfo {
            get {
                return ResourceManager.GetString("DonationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hàng đã hết.
        /// </summary>
        internal static string EmptyGoods {
            get {
                return ResourceManager.GetString("EmptyGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tạo tài hóa đơn. Bạn chờ đợi trong giây lát rồi thử lại.
        /// </summary>
        internal static string ErrorCreateOrder {
            get {
                return ResourceManager.GetString("ErrorCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử.
        /// </summary>
        internal static string eWallet {
            get {
                return ResourceManager.GetString("eWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CỔNG THANH TOÁN ĐIỆN TỬ VTC PAY.
        /// </summary>
        internal static string Footer1 {
            get {
                return ResourceManager.GetString("Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giấy phép hoạt động do NHNN cấp ngày 24/02/2016 - số 31/GP.
        /// </summary>
        internal static string Footer2 {
            get {
                return ResourceManager.GetString("Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đài hỗ trợ: 19001530 / Email: hotro.pay@vtc.vn.
        /// </summary>
        internal static string Footer3 {
            get {
                return ResourceManager.GetString("Footer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string ForgetPass {
            get {
                return ResourceManager.GetString("ForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 3 ngày.
        /// </summary>
        internal static string Hold3day {
            get {
                return ResourceManager.GetString("Hold3day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 5 ngày.
        /// </summary>
        internal static string Hold5day {
            get {
                return ResourceManager.GetString("Hold5day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 7 ngày.
        /// </summary>
        internal static string Hold7day {
            get {
                return ResourceManager.GetString("Hold7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VTC Paygate]Thông báo giao dịch thanh toán ngay.
        /// </summary>
        internal static string ImmediatePayTitle {
            get {
                return ResourceManager.GetString("ImmediatePayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khảu ODP không đúng.
        /// </summary>
        internal static string IncorrectODP {
            get {
                return ResourceManager.GetString("IncorrectODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin khách hàng.
        /// </summary>
        internal static string InfomationCustom {
            get {
                return ResourceManager.GetString("InfomationCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn hàng.
        /// </summary>
        internal static string InfomationOrder {
            get {
                return ResourceManager.GetString("InfomationOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn vị chủ khoản.
        /// </summary>
        internal static string InfomationUnit {
            get {
                return ResourceManager.GetString("InfomationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý dữ liệu....
        /// </summary>
        internal static string InProcessData {
            get {
                return ResourceManager.GetString("InProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tiền.
        /// </summary>
        internal static string InputMoney {
            get {
                return ResourceManager.GetString("InputMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã ODP &lt;b&gt;.
        /// </summary>
        internal static string InputODP {
            get {
                return ResourceManager.GetString("InputODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ODP để hoàn tất thanh toán.
        /// </summary>
        internal static string InputODPPayment {
            get {
                return ResourceManager.GetString("InputODPPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã OTP.
        /// </summary>
        internal static string InputOTP {
            get {
                return ResourceManager.GetString("InputOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập OTP để hoàn tất thanh toán.
        /// </summary>
        internal static string InputOTPPayment {
            get {
                return ResourceManager.GetString("InputOTPPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        internal static string InputPhone {
            get {
                return ResourceManager.GetString("InputPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chức thanh toán quốc tế.
        /// </summary>
        internal static string internationalPayment {
            get {
                return ResourceManager.GetString("internationalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải điền tài khoản Paygate người bán.
        /// </summary>
        internal static string LessAccPGSaler {
            get {
                return ResourceManager.GetString("LessAccPGSaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu mã nút.
        /// </summary>
        internal static string LessButtonCode {
            get {
                return ResourceManager.GetString("LessButtonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu tài khoản eBank của người bán để truyền VCoin vào. Bạn thông báo cho người bán cập nhật tài khoản eBank trong phần thông tin tổng hợp.
        /// </summary>
        internal static string LessEBankAcc {
            get {
                return ResourceManager.GetString("LessEBankAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải truyền tài khoản đăng nhập eBank.
        /// </summary>
        internal static string LessEBankLogin {
            get {
                return ResourceManager.GetString("LessEBankLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập số điện thoại.
        /// </summary>
        internal static string LessPhone {
            get {
                return ResourceManager.GetString("LessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải truyền websiteID.
        /// </summary>
        internal static string LessWebsiteID {
            get {
                return ResourceManager.GetString("LessWebsiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể dủng thẻ liên kết.
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để thanh toán cho đơn hàng này. Vui lòng chọn thẻ liên kết khác.
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư tài khoản không đủ để thanh toán.
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa kích hoạt, vui lòng kích hoạt tại đây.
        /// </summary>
        internal static string MessageAccInActive {
            get {
                return ResourceManager.GetString("MessageAccInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        internal static string MessageAccountIncorect {
            get {
                return ResourceManager.GetString("MessageAccountIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string MessageAccPassFail {
            get {
                return ResourceManager.GetString("MessageAccPassFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thẻ gắn kết, vui lòng chọn thêm thẻ gắn kết mới.
        /// </summary>
        internal static string MessageAttached {
            get {
                return ResourceManager.GetString("MessageAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thẻ trong tài khoản Ví giúp bạn không cần nhập lại thông tin thẻ mỗi lần thanh toán, thẻ được bảo vệ bởi OTP/ODP hoặc 3D-Secure.
        /// </summary>
        internal static string MessageBankCardWallet {
            get {
                return ResourceManager.GetString("MessageBankCardWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Thanh toán có nghĩa bạn đồng ý với.
        /// </summary>
        internal static string MessageBankCardWallet1 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách ví VTC Pay.
        /// </summary>
        internal static string MessageBankCardWallet2 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP đã được gửi đến số điện thoại/email đăng ký dịch vụ. Nếu không nhận được ODP, vui lòng soạn tin theo cú pháp PAY ODP gửi 19001530.
        /// </summary>
        internal static string MessageBankCardWallet3 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thanh toán bằng thẻ quốc tế, vui lòng chọn hình thức thanh toán khác.
        /// </summary>
        internal static string MessageErrorPayInternalCard {
            get {
                return ResourceManager.GetString("MessageErrorPayInternalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thanh toán qua ngân hàng nội địa, vui lòng chọn hình thức thanh toán khác.
        /// </summary>
        internal static string MessageErrorPayment {
            get {
                return ResourceManager.GetString("MessageErrorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu tài khoản Pay đã gắn kết thẻ Quốc tế, vui lòng chọn.
        /// </summary>
        internal static string MessageIf {
            get {
                return ResourceManager.GetString("MessageIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        internal static string MessageIncorectPass {
            get {
                return ResourceManager.GetString("MessageIncorectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập tài khoản và mật khẩu VTCPay.
        /// </summary>
        internal static string MessageInputAcc {
            get {
                return ResourceManager.GetString("MessageInputAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán đã bao gồm cả phí thanh toán.
        /// </summary>
        internal static string MessageNote {
            get {
                return ResourceManager.GetString("MessageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sử dụng thẻ liên kết để thanh toán cho đơn hàng này. Vui lòng chọn số dư ví để thanh toán.
        /// </summary>
        internal static string MessageNotUseAttachedCard {
            get {
                return ResourceManager.GetString("MessageNotUseAttachedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập sai vượt quá số lần cho phép. Mời bạn hôm sau quay lại.
        /// </summary>
        internal static string MessageNumberAllowed {
            get {
                return ResourceManager.GetString("MessageNumberAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thẻ quốc tế để thanh toán.
        /// </summary>
        internal static string MessagePayInternalCard {
            get {
                return ResourceManager.GetString("MessagePayInternalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP đã được gửi đến số điện thoại/email đăng ký dịch vụ. Nếu không nhận được ODP, vui lòng soạn tin theo cú pháp PAY ODP gửi 19001530.
        /// </summary>
        internal static string MessageWalletUp {
            get {
                return ResourceManager.GetString("MessageWalletUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền quyên góp.
        /// </summary>
        internal static string MonneyDonations {
            get {
                return ResourceManager.GetString("MonneyDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền ủng hộ không hợp lệ.
        /// </summary>
        internal static string MonneyInvalidSupport {
            get {
                return ResourceManager.GetString("MonneyInvalidSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền ủng hộ.
        /// </summary>
        internal static string MonneyOfSupporter {
            get {
                return ResourceManager.GetString("MonneyOfSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ủng hộ phải là bội số của 1000.
        /// </summary>
        internal static string MultiplesSupporter {
            get {
                return ResourceManager.GetString("MultiplesSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải nhập số di động.
        /// </summary>
        internal static string MustInputMobile {
            get {
                return ResourceManager.GetString("MustInputMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn hình thức thanh toán.
        /// </summary>
        internal static string MustSelectPaymentType {
            get {
                return ResourceManager.GetString("MustSelectPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn hình thức thanh toán.
        /// </summary>
        internal static string NoSelectPaymentType {
            get {
                return ResourceManager.GetString("NoSelectPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một trong các  phương thức  thanh toán dưới đây để tiếp tục. Tổng tiền thanh toán ứng với mỗi phương thức thanh toán được hiển thị dưới mỗi logo. Để biết chi tiết hướng dẫn thanh toán, vui lòng xem &lt;a href=&quot;https://paygate.vtc.vn/community/huong-dan/quy-trinh-rut-tien-19-98.html&quot;&gt;tại đây...&lt;/a&gt;.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư không đủ để thực hiện giao dịch.
        /// </summary>
        internal static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đã được thanh toán, vui lòng liên hệ với Nhà cung cấp dịch vụ..
        /// </summary>
        internal static string NotEnoughQuota {
            get {
                return ResourceManager.GetString("NotEnoughQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có đánh giá.
        /// </summary>
        internal static string NotRate {
            get {
                return ResourceManager.GetString("NotRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được sử dụng hình thức thanh toán này. Vui lòng liên hệ với quản trị để được hỗ trợ.
        /// </summary>
        internal static string NotSupportTypePayment {
            get {
                return ResourceManager.GetString("NotSupportTypePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chứng thực.
        /// </summary>
        internal static string NotVerify {
            get {
                return ResourceManager.GetString("NotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP.
        /// </summary>
        internal static string ODP {
            get {
                return ResourceManager.GetString("ODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đơn hàng.
        /// </summary>
        internal static string OrderConfirm {
            get {
                return ResourceManager.GetString("OrderConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người nhận tiền.
        /// </summary>
        internal static string PayeeInfomation {
            get {
                return ResourceManager.GetString("PayeeInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua số dư ví.
        /// </summary>
        internal static string PaymentBalanceWallet {
            get {
                return ResourceManager.GetString("PaymentBalanceWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua ví đựng thẻ.
        /// </summary>
        internal static string PaymentBankWallet {
            get {
                return ResourceManager.GetString("PaymentBankWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thất bại.
        /// </summary>
        internal static string PaymentFail {
            get {
                return ResourceManager.GetString("PaymentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CỔNG THANH TOÁN TRỰC TUYẾN.
        /// </summary>
        internal static string PaymentGateway {
            get {
                return ResourceManager.GetString("PaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán ngay.
        /// </summary>
        internal static string PaymentImmediate {
            get {
                return ResourceManager.GetString("PaymentImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán với thẻ quốc tế.
        /// </summary>
        internal static string PaymentInterCard {
            get {
                return ResourceManager.GetString("PaymentInterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán online.
        /// </summary>
        internal static string PaymentOnline {
            get {
                return ResourceManager.GetString("PaymentOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thành công. Thanh toán được bảo đảm bởi VTC Pay.
        /// </summary>
        internal static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán với ngân hàng nội địa.
        /// </summary>
        internal static string PaymentViaInBanks {
            get {
                return ResourceManager.GetString("PaymentViaInBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại người mua.
        /// </summary>
        internal static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại là căn cứ rà soát,hoàn tiền..
        /// </summary>
        internal static string PhoneTitle {
            get {
                return ResourceManager.GetString("PhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản người bán và người mua phải khác nhau.
        /// </summary>
        internal static string PhonsesSame {
            get {
                return ResourceManager.GetString("PhonsesSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị đơn hàng.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uy tín.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nap tien qua ngan hang.
        /// </summary>
        internal static string RechargeMoneyByBank {
            get {
                return ResourceManager.GetString("RechargeMoneyByBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu chi tiết:.
        /// </summary>
        internal static string RequireDetail {
            get {
                return ResourceManager.GetString("RequireDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string SalerStatus {
            get {
                return ResourceManager.GetString("SalerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngân hàng để thanh toán.
        /// </summary>
        internal static string SectionBank {
            get {
                return ResourceManager.GetString("SectionBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng lựa chọn hình thức thanh toán.
        /// </summary>
        internal static string SelectPaymentMethod {
            get {
                return ResourceManager.GetString("SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà cung cấp.
        /// </summary>
        internal static string SellerInfomation {
            get {
                return ResourceManager.GetString("SellerInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gía trị đơn hàng quá nhỏ. Đơn hàng tối thiểu phải từ 3000 trở lên.
        /// </summary>
        internal static string SmallOrder {
            get {
                return ResourceManager.GetString("SmallOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        internal static string SupplierName {
            get {
                return ResourceManager.GetString("SupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ủng hộ.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người ủng hộ.
        /// </summary>
        internal static string SupporterInfo {
            get {
                return ResourceManager.GetString("SupporterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tôi đã đọc và đồng ý với.
        /// </summary>
        internal static string TermNote1 {
            get {
                return ResourceManager.GetString("TermNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to điều khoản sử dụng.
        /// </summary>
        internal static string TermNote2 {
            get {
                return ResourceManager.GetString("TermNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cổng thanh toán VTCPay.
        /// </summary>
        internal static string TermNote3 {
            get {
                return ResourceManager.GetString("TermNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán đơn hàng.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanh toán hóa đơn, đơn hàng, chọn hình thức thanh toán.
        /// </summary>
        internal static string TitleSeo {
            get {
                return ResourceManager.GetString("TitleSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần điền chính xác số điện thoại của bạn để nhận được tiền trong trường hợp giao dịch không thành công.
        /// </summary>
        internal static string ToolTipBuyerPhone_Text {
            get {
                return ResourceManager.GetString("ToolTipBuyerPhone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền:.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền .
        /// </summary>
        internal static string TotalMonney {
            get {
                return ResourceManager.GetString("TotalMonney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị ủng hộ phải từ 10000đ($0.5) trở lên.
        /// </summary>
        internal static string ValueSupporter {
            get {
                return ResourceManager.GetString("ValueSupporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chứng thực.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTC eBank.
        /// </summary>
        internal static string VTCeBank {
            get {
                return ResourceManager.GetString("VTCeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử VTC Pay.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÍ ĐIỆN TỬ VTC PAY.
        /// </summary>
        internal static string WalletUpper {
            get {
                return ResourceManager.GetString("WalletUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chữ ký sai.
        /// </summary>
        internal static string WrongSignature {
            get {
                return ResourceManager.GetString("WrongSignature", resourceCulture);
            }
        }
    }
}
