//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Profile.Account", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng truy nhập email để hoàn tất kích hoạt mật khẩu mới.
        /// </summary>
        internal static string AccessEmail {
            get {
                return ResourceManager.GetString("AccessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản doanh nghiệp.
        /// </summary>
        internal static string AccountBusiness {
            get {
                return ResourceManager.GetString("AccountBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hiện đang bị khóa.
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        internal static string AccountNotExists {
            get {
                return ResourceManager.GetString("AccountNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        internal static string AccountNotValid {
            get {
                return ResourceManager.GetString("AccountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản cá nhân.
        /// </summary>
        internal static string AccountPersonal {
            get {
                return ResourceManager.GetString("AccountPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hợp lệ.
        /// </summary>
        internal static string AccountValid {
            get {
                return ResourceManager.GetString("AccountValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được chứng thực rồi.
        /// </summary>
        internal static string AccountValided {
            get {
                return ResourceManager.GetString("AccountValided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử này đã chứng thực, không thể thực hiện chuyển đổi sang loại Ví điện tử khác.
        /// </summary>
        internal static string AccountValidedNotDo {
            get {
                return ResourceManager.GetString("AccountValidedNotDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bạn cung cấp không hợp lệ. Vui lòng thử lại sau..
        /// </summary>
        internal static string DataNotValid {
            get {
                return ResourceManager.GetString("DataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn đã được chứng thực rồi.
        /// </summary>
        internal static string EmailAuthened {
            get {
                return ResourceManager.GetString("EmailAuthened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã tồn tại rồi.
        /// </summary>
        internal static string EmailExisted {
            get {
                return ResourceManager.GetString("EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email của bạn chưa được chứng thực.
        /// </summary>
        internal static string EmailNotAuthened {
            get {
                return ResourceManager.GetString("EmailNotAuthened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập địa chỉ email.
        /// </summary>
        internal static string EmailNotEnter {
            get {
                return ResourceManager.GetString("EmailNotEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email tài khoản không chính xác.
        /// </summary>
        internal static string EmailNotExactly {
            get {
                return ResourceManager.GetString("EmailNotExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ.
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Data Key đã mã hóa.
        /// </summary>
        internal static string EnterKeyData {
            get {
                return ResourceManager.GetString("EnterKeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Partner Key đã mã hóa.
        /// </summary>
        internal static string EnterKeyPartner {
            get {
                return ResourceManager.GetString("EnterKeyPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui upload ảnh để chứng thực tài khoản.
        /// </summary>
        internal static string ImagesUpdateValid {
            get {
                return ResourceManager.GetString("ImagesUpdateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã từng thực hiện gửi ảnh xác thực, vui lòng đợi phản hồi từ nhà quản trị..
        /// </summary>
        internal static string ImagesValided {
            get {
                return ResourceManager.GetString("ImagesValided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ không đúng.
        /// </summary>
        internal static string OldPasswordError {
            get {
                return ResourceManager.GetString("OldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển sang đăng nhập email openid theo url trả về.
        /// </summary>
        internal static string OpenidEmailReturn {
            get {
                return ResourceManager.GetString("OpenidEmailReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không dùng OTP ma trận. Vui lòng chọn hình thức khác.
        /// </summary>
        internal static string OTPNotUse {
            get {
                return ResourceManager.GetString("OTPNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không hợp lệ.
        /// </summary>
        internal static string OTPNotValid {
            get {
                return ResourceManager.GetString("OTPNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả về vị trí OTP ma trận cần nhập.
        /// </summary>
        internal static string OTPReturn {
            get {
                return ResourceManager.GetString("OTPReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP hợp lệ, gửi về link trong Extened.
        /// </summary>
        internal static string OTPValidExtend {
            get {
                return ResourceManager.GetString("OTPValidExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải từ 6- 18 ký tự. Bao gồm cả chữ cái và số.
        /// </summary>
        internal static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đổi tài khoản thành công.
        /// </summary>
        internal static string SuccessChangeAccount {
            get {
                return ResourceManager.GetString("SuccessChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã lấy lại mật khẩu thành công.
        /// </summary>
        internal static string SuccessGetPass {
            get {
                return ResourceManager.GetString("SuccessGetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin chứng thực tài khoản thành công.
        /// </summary>
        internal static string SuccessSendValid {
            get {
                return ResourceManager.GetString("SuccessSendValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin tài khoản thành công.
        /// </summary>
        internal static string SuccessUpdateAcc {
            get {
                return ResourceManager.GetString("SuccessUpdateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kết nối thành công.
        /// </summary>
        internal static string SuccessUpdateConnect {
            get {
                return ResourceManager.GetString("SuccessUpdateConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã đổi mật khẩu thành công.
        /// </summary>
        internal static string SuccessUpdatePass {
            get {
                return ResourceManager.GetString("SuccessUpdatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc mừng bạn đã chứng thực email thành công.
        /// </summary>
        internal static string SuccessValidEmail {
            get {
                return ResourceManager.GetString("SuccessValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui lòng quay lại sau ít phút.
        /// </summary>
        internal static string SystemBusy {
            get {
                return ResourceManager.GetString("SystemBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng đăng nhập để thực hiện chức năng này.
        /// </summary>
        internal static string UnLogin {
            get {
                return ResourceManager.GetString("UnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi thông tin chứng thực không thành công. Bạn vui lòng quay lại sau.
        /// </summary>
        internal static string UnSuccessSendValid {
            get {
                return ResourceManager.GetString("UnSuccessSendValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng thực không thành công.Bạn vui lòng quay lại sau.
        /// </summary>
        internal static string UnSuccessValidEmail {
            get {
                return ResourceManager.GetString("UnSuccessValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng cập nhật và chứng thực email.
        /// </summary>
        internal static string UpdateAndValidEmail {
            get {
                return ResourceManager.GetString("UpdateAndValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng cập nhật địa chỉ email trước.
        /// </summary>
        internal static string UpdateEmailBefore {
            get {
                return ResourceManager.GetString("UpdateEmailBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng cập nhật địa chỉ email trước khi chuyển đổi.
        /// </summary>
        internal static string UpdateEmailBeforeChange {
            get {
                return ResourceManager.GetString("UpdateEmailBeforeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng cập nhật địa chỉ email trước khi chứng thực.
        /// </summary>
        internal static string UpdateEmailBeforeValid {
            get {
                return ResourceManager.GetString("UpdateEmailBeforeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng chứng thực email trước khi chứng thực tài khoản.
        /// </summary>
        internal static string ValidEmailBefore {
            get {
                return ResourceManager.GetString("ValidEmailBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng thực không thành công.Dữ liệu bạn cung cấp không hợp lệ.
        /// </summary>
        internal static string ValidNotData {
            get {
                return ResourceManager.GetString("ValidNotData", resourceCulture);
            }
        }
    }
}
