//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PayWallet
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayWallet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PayWallet", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư ví.
        /// </summary>
        internal static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        internal static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lại ODP.
        /// </summary>
        internal static string btnGetODP {
            get {
                return ResourceManager.GetString("btnGetODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng Nhập.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        internal static string btnPayment {
            get {
                return ResourceManager.GetString("btnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đăng ký tại đây.
        /// </summary>
        internal static string btnRegisterHere {
            get {
                return ResourceManager.GetString("btnRegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Captcha.
        /// </summary>
        internal static string CaptchaCode {
            get {
                return ResourceManager.GetString("CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên thông tin đăng nhập?.
        /// </summary>
        internal static string Forgotpassword {
            get {
                return ResourceManager.GetString("Forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào email.
        /// </summary>
        internal static string ODPCheckEmail {
            get {
                return ResourceManager.GetString("ODPCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ ma trận đã được gửi khi bạn đăng ký OTP ma trận. Vui lòng kiểm tra lại.
        /// </summary>
        internal static string ODPCheckMatrix {
            get {
                return ResourceManager.GetString("ODPCheckMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODP đang được gửi, bạn vui lòng chờ.
        /// </summary>
        internal static string ODPCheckService {
            get {
                return ResourceManager.GetString("ODPCheckService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào số điện thoại của bạn.
        /// </summary>
        internal static string ODPCheckSMS {
            get {
                return ResourceManager.GetString("ODPCheckSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi ngày chỉ nhận tối đa 3 lần ODP SMS.
        /// </summary>
        internal static string ODPCheckTime {
            get {
                return ResourceManager.GetString("ODPCheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã xác minh ODP.
        /// </summary>
        internal static string ODPcode {
            get {
                return ResourceManager.GetString("ODPcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các phương thức thanh toán khác.
        /// </summary>
        internal static string OtherPaymentmethod {
            get {
                return ResourceManager.GetString("OtherPaymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã xác minh OTP.
        /// </summary>
        internal static string OTPcode {
            get {
                return ResourceManager.GetString("OTPcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP ma trận.
        /// </summary>
        internal static string OTPMatrix {
            get {
                return ResourceManager.GetString("OTPMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thanh toán .
        /// </summary>
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua thẻ gắn kết.
        /// </summary>
        internal static string PaymentMountCard {
            get {
                return ResourceManager.GetString("PaymentMountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua số dư ví.
        /// </summary>
        internal static string PaymentVTCPayBalance {
            get {
                return ResourceManager.GetString("PaymentVTCPayBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa có tài khoản?.
        /// </summary>
        internal static string titleHaveAccount {
            get {
                return ResourceManager.GetString("titleHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử VTC Pay.
        /// </summary>
        internal static string VTCPayEWallet {
            get {
                return ResourceManager.GetString("VTCPayEWallet", resourceCulture);
            }
        }
    }
}
