//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Checkout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Checkout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Checkout", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa có thông tin số điện thoại liên hệ!.
        /// </summary>
        internal static string AccMsg1 {
            get {
                return ResourceManager.GetString("AccMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string AccountNotExits {
            get {
                return ResourceManager.GetString("AccountNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận tiền không tồn tại.
        /// </summary>
        internal static string AccountReceiveNotExist {
            get {
                return ResourceManager.GetString("AccountReceiveNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản VTC.
        /// </summary>
        internal static string AccountVTC {
            get {
                return ResourceManager.GetString("AccountVTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Paygate người nhận không tồn tại. Bạn vui lòng kiểm tra lại dữ liệu.
        /// </summary>
        internal static string AccSalerNotExits {
            get {
                return ResourceManager.GetString("AccSalerNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thẻ.
        /// </summary>
        internal static string AddCard {
            get {
                return ResourceManager.GetString("AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ: 23 Lạc Trung, Hai Bà Trưng, Hà Nội.
        /// </summary>
        internal static string AddressInfo {
            get {
                return ResourceManager.GetString("AddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư khả dụng.
        /// </summary>
        internal static string AvailableBalances {
            get {
                return ResourceManager.GetString("AvailableBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư tài khoản không đủ để thanh toán.
        /// </summary>
        internal static string BalanceNotEnough {
            get {
                return ResourceManager.GetString("BalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví dựng thẻ.
        /// </summary>
        internal static string BankCardWallet {
            get {
                return ResourceManager.GetString("BankCardWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string BuyerEmail {
            get {
                return ResourceManager.GetString("BuyerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người mua.
        /// </summary>
        internal static string BuyerName {
            get {
                return ResourceManager.GetString("BuyerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số di động.
        /// </summary>
        internal static string BuyerPhone {
            get {
                return ResourceManager.GetString("BuyerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string Cancel1 {
            get {
                return ResourceManager.GetString("Cancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đã bị hủy.
        /// </summary>
        internal static string CancelTransaction {
            get {
                return ResourceManager.GetString("CancelTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        internal static string CardCode {
            get {
                return ResourceManager.GetString("CardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chipset.
        /// </summary>
        internal static string ChipsetCode {
            get {
                return ResourceManager.GetString("ChipsetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu truyền lên không hợp lệ. Bạn vui lòng kiểm tra lại.
        /// </summary>
        internal static string DataTransferInvalid {
            get {
                return ResourceManager.GetString("DataTransferInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhận hàng.
        /// </summary>
        internal static string DeliveryAddresss {
            get {
                return ResourceManager.GetString("DeliveryAddresss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng đã bị trùng. Vui lòng tạo lại đơn hàng mới.
        /// </summary>
        internal static string DuplicateOrderCode {
            get {
                return ResourceManager.GetString("DuplicateOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch trùng lặp, Vui lòng kiểm tra lại.
        /// </summary>
        internal static string DuplicateOrders {
            get {
                return ResourceManager.GetString("DuplicateOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không đúng định dạng đầu số di động Việt Nam. Bạn vui lòng nhập email để tra soát giao dịch.
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá xử lý. Vui lòng liên hệ CSKH để xử lý.
        /// </summary>
        internal static string ErrGetPassLogin {
            get {
                return ResourceManager.GetString("ErrGetPassLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi tạo đơn hàng. Bạn chờ đợi trong giây lát rồi thử lại.
        /// </summary>
        internal static string ErrorCreateOrder {
            get {
                return ResourceManager.GetString("ErrorCreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi lần click nhận lại ODP SMS phải cách nhau 30s.
        /// </summary>
        internal static string ERR_ODP_SMS_SPAM {
            get {
                return ResourceManager.GetString("ERR_ODP_SMS_SPAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi ngày chỉ nhận tối đa 3 lần ODP SMS.
        /// </summary>
        internal static string ERR_OVER_LIMIT_ODP_SMS_IN_DAY {
            get {
                return ResourceManager.GetString("ERR_OVER_LIMIT_ODP_SMS_IN_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử.
        /// </summary>
        internal static string eWallet {
            get {
                return ResourceManager.GetString("eWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        internal static string ExpriedDate {
            get {
                return ResourceManager.GetString("ExpriedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTC Corporation. All rights reserved..
        /// </summary>
        internal static string Footer1 {
            get {
                return ResourceManager.GetString("Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tầng 15, Tòa nhà VTC, 23 Lạc Trung, Hai Bà Trưng, Hà Nội.&lt;br/&gt;Giấy phép hoạt động số 31/GP-NHNN.
        /// </summary>
        internal static string Footer2 {
            get {
                return ResourceManager.GetString("Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đài hỗ trợ: 19001530 / support: http://hotro.vtc.vn.
        /// </summary>
        internal static string Footer3 {
            get {
                return ResourceManager.GetString("Footer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lại mã xác thực.
        /// </summary>
        internal static string GetBackSmsOdp {
            get {
                return ResourceManager.GetString("GetBackSmsOdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đang xử lý.
        /// </summary>
        internal static string HandlTrans {
            get {
                return ResourceManager.GetString("HandlTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tại đây.
        /// </summary>
        internal static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 3 ngày.
        /// </summary>
        internal static string Hold3day {
            get {
                return ResourceManager.GetString("Hold3day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 5 ngày.
        /// </summary>
        internal static string Hold5day {
            get {
                return ResourceManager.GetString("Hold5day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạm giữ 7 ngày.
        /// </summary>
        internal static string Hold7day {
            get {
                return ResourceManager.GetString("Hold7day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật không đúng. Bạn vui lòng nhập lại.
        /// </summary>
        internal static string IncorrectODP {
            get {
                return ResourceManager.GetString("IncorrectODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string IncorrectPhone {
            get {
                return ResourceManager.GetString("IncorrectPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã OTP ma trận theo ô: &lt;b&gt;.
        /// </summary>
        internal static string InputMatrix {
            get {
                return ResourceManager.GetString("InputMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã ODP theo ô: &lt;b&gt;.
        /// </summary>
        internal static string InputODP {
            get {
                return ResourceManager.GetString("InputODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã bảo mật để hoàn tất thanh toán.
        /// </summary>
        internal static string InputODPPayment {
            get {
                return ResourceManager.GetString("InputODPPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng mở app VTCPay OTP để lấy mã OTP.
        /// </summary>
        internal static string InputOTP {
            get {
                return ResourceManager.GetString("InputOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập OTP để hoàn tất thanh toán.
        /// </summary>
        internal static string InputOTPPayment {
            get {
                return ResourceManager.GetString("InputOTPPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chức thanh toán quốc tế.
        /// </summary>
        internal static string internationalPayment {
            get {
                return ResourceManager.GetString("internationalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải điền tài khoản EBank người bán.
        /// </summary>
        internal static string LessAccEBSaler {
            get {
                return ResourceManager.GetString("LessAccEBSaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải điền tài khoản Paygate người bán.
        /// </summary>
        internal static string LessAccPGSaler {
            get {
                return ResourceManager.GetString("LessAccPGSaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải truyền tài khoản đăng nhập eBank.
        /// </summary>
        internal static string LessEBankLogin {
            get {
                return ResourceManager.GetString("LessEBankLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập số điện thoại.
        /// </summary>
        internal static string LessPhone {
            get {
                return ResourceManager.GetString("LessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải truyền websiteID.
        /// </summary>
        internal static string LessWebsiteID {
            get {
                return ResourceManager.GetString("LessWebsiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa kích hoạt, vui lòng kích hoạt tại đây.
        /// </summary>
        internal static string MessageAccInActive {
            get {
                return ResourceManager.GetString("MessageAccInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        internal static string MessageAccountIncorect {
            get {
                return ResourceManager.GetString("MessageAccountIncorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        internal static string MessageAccPassFail {
            get {
                return ResourceManager.GetString("MessageAccPassFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thẻ gắn kết, vui lòng chọn thêm thẻ gắn kết mới.
        /// </summary>
        internal static string MessageAttached {
            get {
                return ResourceManager.GetString("MessageAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sử dụng thẻ liên kết.
        /// </summary>
        internal static string MessageAttached1 {
            get {
                return ResourceManager.GetString("MessageAttached1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để thanh toán cho đơn hàng này. Vui lòng chọn thẻ liên kết khác.
        /// </summary>
        internal static string MessageAttached2 {
            get {
                return ResourceManager.GetString("MessageAttached2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thẻ trong tài khoản Ví giúp bạn không cần nhập lại thông tin thẻ mỗi lần thanh toán, thẻ được bảo vệ bởi OTP/ODP hoặc 3D-Secure.
        /// </summary>
        internal static string MessageBankCardWallet {
            get {
                return ResourceManager.GetString("MessageBankCardWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Thanh toán có nghĩa bạn đồng ý với.
        /// </summary>
        internal static string MessageBankCardWallet1 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách ví VTC Pay.
        /// </summary>
        internal static string MessageBankCardWallet2 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP đã được gửi đến số điện thoại/email đăng ký dịch vụ. Nếu không nhận được ODP, vui lòng soạn tin theo cú pháp PAY ODP gửi 19001530.
        /// </summary>
        internal static string MessageBankCardWallet3 {
            get {
                return ResourceManager.GetString("MessageBankCardWallet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to của quý khách đã được gia hạn thành công, thời hạn thuê bao mới đến hết ngày.
        /// </summary>
        internal static string MessageChanels {
            get {
                return ResourceManager.GetString("MessageChanels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thanh toán bằng thẻ quốc tế, vui lòng chọn hình thức thanh toán khác.
        /// </summary>
        internal static string MessageErrorPayInternalCard {
            get {
                return ResourceManager.GetString("MessageErrorPayInternalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thanh toán qua ngân hàng nội địa, vui lòng chọn hình thức thanh toán khác.
        /// </summary>
        internal static string MessageErrorPayment {
            get {
                return ResourceManager.GetString("MessageErrorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu tài khoản Pay đã gắn kết thẻ Quốc tế, vui lòng chọn.
        /// </summary>
        internal static string MessageIf {
            get {
                return ResourceManager.GetString("MessageIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không chính xác.
        /// </summary>
        internal static string MessageIncorectPass {
            get {
                return ResourceManager.GetString("MessageIncorectPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản không hợp lệ.
        /// </summary>
        internal static string MessageInputAcc {
            get {
                return ResourceManager.GetString("MessageInputAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán đã bao gồm cả phí thanh toán.
        /// </summary>
        internal static string MessageNote {
            get {
                return ResourceManager.GetString("MessageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sử dụng thẻ liên kết để thanh toán cho đơn hàng này. Vui lòng chọn số dư ví để thanh toán.
        /// </summary>
        internal static string MessageNotUseAttachedCard {
            get {
                return ResourceManager.GetString("MessageNotUseAttachedCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập sai vượt quá số lần cho phép. Mời bạn hôm sau quay lại.
        /// </summary>
        internal static string MessageNumberAllowed {
            get {
                return ResourceManager.GetString("MessageNumberAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn thẻ quốc tế để thanh toán.
        /// </summary>
        internal static string MessagePayInternalCard {
            get {
                return ResourceManager.GetString("MessagePayInternalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại là căn cứ tra soát, hoàn tiền.
        /// </summary>
        internal static string MessagePhoneForRefund {
            get {
                return ResourceManager.GetString("MessagePhoneForRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán bằng thẻ cào trả trước không được hưởng chiết khấu gia hạn..
        /// </summary>
        internal static string MessagePrepaidCard1 {
            get {
                return ResourceManager.GetString("MessagePrepaidCard1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ đã thanh toán không có giá trị sử dụng lại, số dư nạp thẻ được cộng vào tài khoản đầu thu.
        /// </summary>
        internal static string MessagePrepaidCard2 {
            get {
                return ResourceManager.GetString("MessagePrepaidCard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các loại thẻ viễn thông (Mobifone, Vinaphone, Viettel) chỉ được ghi nhận 90% giá trị thẻ nạp.
        /// </summary>
        internal static string MessagePrepaidCard3 {
            get {
                return ResourceManager.GetString("MessagePrepaidCard3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán bằng số dư tài khoản VTC không được hưởng chiết khấu gia hạn..
        /// </summary>
        internal static string MessageVTCAccount1 {
            get {
                return ResourceManager.GetString("MessageVTCAccount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý: Tỷ giá chuyển đổi: 1 Vcoin = 1000 VND..
        /// </summary>
        internal static string MessageVTCAccount2 {
            get {
                return ResourceManager.GetString("MessageVTCAccount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp dùng ODP bảo mật, ODP đã được gửi đến số điện thoại/email đăng ký dịch vụ. Nếu không nhận được, vui lòng soạn tin theo cú pháp PAY ODP gửi Tổng đài hỗ trợ 19001530.
        /// </summary>
        internal static string MessageWalletUp {
            get {
                return ResourceManager.GetString("MessageWalletUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn hiện chưa đăng kí hình thức bảo mật nào, để có thể thực hiện giao dịch hoặc thay đổi thông tin bảo mật, Vui lòng vào mục cài đặt để thực hiện đăng ký bảo mật..
        /// </summary>
        internal static string MissSecure {
            get {
                return ResourceManager.GetString("MissSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Mobifone.
        /// </summary>
        internal static string MobifoneCard {
            get {
                return ResourceManager.GetString("MobifoneCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang có {0} VNĐ trong tài khoản khả dụng. Bạn có thực sự muốn thực hiện gói gia hạn này không?.
        /// </summary>
        internal static string Msg1 {
            get {
                return ResourceManager.GetString("Msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ cào không hợp lệ ,xin vui lòng kiểm tra lại.
        /// </summary>
        internal static string MsgCard {
            get {
                return ResourceManager.GetString("MsgCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý:.
        /// </summary>
        internal static string MsgNote {
            get {
                return ResourceManager.GetString("MsgNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ tài khoản.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn hình thức thanh toán.
        /// </summary>
        internal static string NoSelectPaymentType {
            get {
                return ResourceManager.GetString("NoSelectPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ. Vui lòng liên hệ quản trị để được hỗ trợ.
        /// </summary>
        internal static string NotAllowLogin {
            get {
                return ResourceManager.GetString("NotAllowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một trong các  phương thức  thanh toán dưới đây để tiếp tục. Tổng tiền thanh toán ứng với mỗi phương thức thanh toán được hiển thị dưới mỗi logo. Để biết chi tiết hướng dẫn thanh toán, vui lòng xem &lt;a href=&quot;#&quot;&gt;tại đây...&lt;/a&gt;.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư không đủ để thực hiện giao dịch.
        /// </summary>
        internal static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không lấy được thông tin đơn hàng.
        /// </summary>
        internal static string NotGetOrderInfo {
            get {
                return ResourceManager.GetString("NotGetOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP đã được gửi tới Email .
        /// </summary>
        internal static string NotifyODPEmail {
            get {
                return ResourceManager.GetString("NotifyODPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP đã được gửi về số điện thoại.
        /// </summary>
        internal static string NotifyODPSMS {
            get {
                return ResourceManager.GetString("NotifyODPSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được gửi tới Email .
        /// </summary>
        internal static string NotifyOTPEmail {
            get {
                return ResourceManager.GetString("NotifyOTPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã được gửi về số điện thoại.
        /// </summary>
        internal static string NotifyOTPSMS {
            get {
                return ResourceManager.GetString("NotifyOTPSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có đánh giá.
        /// </summary>
        internal static string NotRate {
            get {
                return ResourceManager.GetString("NotRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được sử dụng hình thức thanh toán này. Vui lòng liên hệ với quản trị để được hỗ trợ.
        /// </summary>
        internal static string NotSupportTypePayment {
            get {
                return ResourceManager.GetString("NotSupportTypePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chứng thực.
        /// </summary>
        internal static string NotVerify {
            get {
                return ResourceManager.GetString("NotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ODP.
        /// </summary>
        internal static string ODP {
            get {
                return ResourceManager.GetString("ODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        internal static string OrderCode {
            get {
                return ResourceManager.GetString("OrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn hàng không hợp lệ. Vui lòng kiểm tra lại !.
        /// </summary>
        internal static string OrderInfoInvalid {
            get {
                return ResourceManager.GetString("OrderInfoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đơn hàng.
        /// </summary>
        internal static string OrderInfomation {
            get {
                return ResourceManager.GetString("OrderInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng không tồn tại.
        /// </summary>
        internal static string OrderNotExist {
            get {
                return ResourceManager.GetString("OrderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói kênh.
        /// </summary>
        internal static string PackageChannels {
            get {
                return ResourceManager.GetString("PackageChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua số dư ví.
        /// </summary>
        internal static string PaymentBalanceWallet {
            get {
                return ResourceManager.GetString("PaymentBalanceWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán qua ví đựng thẻ.
        /// </summary>
        internal static string PaymentBankWallet {
            get {
                return ResourceManager.GetString("PaymentBankWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình giao dịch. Bạn vui lòng kiểm tra lại để biết chính xác giao dịch thành công hay thất bại.
        /// </summary>
        internal static string PaymentConfuse {
            get {
                return ResourceManager.GetString("PaymentConfuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thất bại.
        /// </summary>
        internal static string PaymentFail {
            get {
                return ResourceManager.GetString("PaymentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CỔNG THANH TOÁN TRỰC TUYẾN.
        /// </summary>
        internal static string PaymentGate {
            get {
                return ResourceManager.GetString("PaymentGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán ngay.
        /// </summary>
        internal static string PaymentImmediate {
            get {
                return ResourceManager.GetString("PaymentImmediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN THANH TOÁN.
        /// </summary>
        internal static string PaymentInfomationUp {
            get {
                return ResourceManager.GetString("PaymentInfomationUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán với thẻ quốc tế.
        /// </summary>
        internal static string PaymentInterCard {
            get {
                return ResourceManager.GetString("PaymentInterCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức thanh toán.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán thành công.
        /// </summary>
        internal static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán với ngân hàng nội địa.
        /// </summary>
        internal static string PaymentViaInBanks {
            get {
                return ResourceManager.GetString("PaymentViaInBanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại người mua không hợp lệ.
        /// </summary>
        internal static string PhoneNotValid {
            get {
                return ResourceManager.GetString("PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản người bán và người mua phải khác nhau.
        /// </summary>
        internal static string PhonsesSame {
            get {
                return ResourceManager.GetString("PhonsesSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        internal static string PleaseInputPhone {
            get {
                return ResourceManager.GetString("PleaseInputPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ cào trả trước.
        /// </summary>
        internal static string PrepaidCard {
            get {
                return ResourceManager.GetString("PrepaidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà cung cấp.
        /// </summary>
        internal static string ProviderInfo {
            get {
                return ResourceManager.GetString("ProviderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uy tín.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng trùng lặp.
        /// </summary>
        internal static string RepeaterOrder {
            get {
                return ResourceManager.GetString("RepeaterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu chi tiết:.
        /// </summary>
        internal static string RequireDetail {
            get {
                return ResourceManager.GetString("RequireDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải nhập email để gửi thông tin giao dịch.
        /// </summary>
        internal static string RequireEmail {
            get {
                return ResourceManager.GetString("RequireEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string SalerStatus {
            get {
                return ResourceManager.GetString("SalerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngân hàng để thanh toán.
        /// </summary>
        internal static string SectionBank {
            get {
                return ResourceManager.GetString("SectionBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng lựa chọn một phương thức thanh toán.
        /// </summary>
        internal static string SelectPayment {
            get {
                return ResourceManager.GetString("SelectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số serial thẻ.
        /// </summary>
        internal static string SerialCard {
            get {
                return ResourceManager.GetString("SerialCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã dịch vụ.
        /// </summary>
        internal static string ServiceCode {
            get {
                return ResourceManager.GetString("ServiceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin dịch vụ cung cấp.
        /// </summary>
        internal static string ServiceInfo {
            get {
                return ResourceManager.GetString("ServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói dịch vụ.
        /// </summary>
        internal static string ServicePack {
            get {
                return ResourceManager.GetString("ServicePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết phiên giao dịch.
        /// </summary>
        internal static string SessionTimeOut {
            get {
                return ResourceManager.GetString("SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đầu thu.
        /// </summary>
        internal static string SettopBoxType {
            get {
                return ResourceManager.GetString("SettopBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gía trị đơn hàng quá nhỏ. Đơn hàng tối thiểu phải từ 10000 trở lên.
        /// </summary>
        internal static string SmallOrder {
            get {
                return ResourceManager.GetString("SmallOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thành công.
        /// </summary>
        internal static string SuccessTrans {
            get {
                return ResourceManager.GetString("SuccessTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán đơn hàng.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Là số dư VNĐ trong tài khoản Mã dịch vụ còn lại từ những lần gia hạn trước đó.
        /// </summary>
        internal static string TitleComment {
            get {
                return ResourceManager.GetString("TitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanh toán hóa đơn, đơn hàng, chọn hình thức thanh toán.
        /// </summary>
        internal static string TitleSeo {
            get {
                return ResourceManager.GetString("TitleSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần điền chính xác số điện thoại của bạn để nhận được tiền trong trường hợp giao dịch không thành công.
        /// </summary>
        internal static string ToolTipBuyerPhone_Text {
            get {
                return ResourceManager.GetString("ToolTipBuyerPhone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email để nhận thông báo và tra soát giao dịch.
        /// </summary>
        internal static string TooltipInputEmail {
            get {
                return ResourceManager.GetString("TooltipInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string TotalPayment {
            get {
                return ResourceManager.GetString("TotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đang xử lý.
        /// </summary>
        internal static string TransProcessing {
            get {
                return ResourceManager.GetString("TransProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thẻ.
        /// </summary>
        internal static string TypeCard {
            get {
                return ResourceManager.GetString("TypeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ thuê bao.
        /// </summary>
        internal static string UserSubscribers {
            get {
                return ResourceManager.GetString("UserSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Vcoin.
        /// </summary>
        internal static string VcoinCard {
            get {
                return ResourceManager.GetString("VcoinCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng thực.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Viettel.
        /// </summary>
        internal static string ViettelCard {
            get {
                return ResourceManager.GetString("ViettelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Vinaphone.
        /// </summary>
        internal static string VinaphoneCard {
            get {
                return ResourceManager.GetString("VinaphoneCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ VTCDigital.
        /// </summary>
        internal static string VTCDigitalCard {
            get {
                return ResourceManager.GetString("VTCDigitalCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VTC eBank.
        /// </summary>
        internal static string VTCeBank {
            get {
                return ResourceManager.GetString("VTCeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử VTC Pay.
        /// </summary>
        internal static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VÍ ĐIỆN TỬ VTC PAY.
        /// </summary>
        internal static string WalletUpper {
            get {
                return ResourceManager.GetString("WalletUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông số tích hợp của Merchant không hợp lệ.
        /// </summary>
        internal static string WebsiteIntegratedInvalid {
            get {
                return ResourceManager.GetString("WebsiteIntegratedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website tích hợp không tồn tại.
        /// </summary>
        internal static string WebsiteNotExits {
            get {
                return ResourceManager.GetString("WebsiteNotExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chữ ký không đúng hoặc đã hết hạn.
        /// </summary>
        internal static string WrongSignature {
            get {
                return ResourceManager.GetString("WrongSignature", resourceCulture);
            }
        }
    }
}
