//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OnlineBanking {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OnlineBanking() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OnlineBanking", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ thẻ.
        /// </summary>
        internal static string AccountHolder {
            get {
                return ResourceManager.GetString("AccountHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ ATM.
        /// </summary>
        internal static string ATMCardNumber {
            get {
                return ResourceManager.GetString("ATMCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng không hoạt động.
        /// </summary>
        internal static string BankAccInActive {
            get {
                return ResourceManager.GetString("BankAccInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được phép thanh toán. Vui lòng liên hệ tổng đài TTCSKH BIDV theo số điện thoại 19009247 để được hỗ trợ..
        /// </summary>
        internal static string BankAccNotAlowedPayment {
            get {
                return ResourceManager.GetString("BankAccNotAlowedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tiền thanh toán tại ngân hàng vượt quá hạn mức trong ngày.
        /// </summary>
        internal static string BankAmountOverLitmitDay {
            get {
                return ResourceManager.GetString("BankAmountOverLitmitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng không đủ số dư để thanh toán.
        /// </summary>
        internal static string BankNotEnoughBalance {
            get {
                return ResourceManager.GetString("BankNotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng chưa đăng ký dịch vụ tại ngân hàng.
        /// </summary>
        internal static string BankNotRegisterService {
            get {
                return ResourceManager.GetString("BankNotRegisterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số giao dịch tại ngân hàng vượt quá hạn mức ngày.
        /// </summary>
        internal static string BankTransOverLimitDay {
            get {
                return ResourceManager.GetString("BankTransOverLimitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        internal static string btnPayment {
            get {
                return ResourceManager.GetString("btnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập sai thông tin thẻ. Bạn được nhập lại thêm 2 lần nữa !.
        /// </summary>
        internal static string CardInfoInputInvalid {
            get {
                return ResourceManager.GetString("CardInfoInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập sai thông tin thẻ. Bạn được nhập lại thêm 1 lần nữa !.
        /// </summary>
        internal static string CardInfoInputInvalid1 {
            get {
                return ResourceManager.GetString("CardInfoInputInvalid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thẻ thanh toán không hợp lệ.
        /// </summary>
        internal static string CardInfoInvalid {
            get {
                return ResourceManager.GetString("CardInfoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ không đủ điều kiện giao dịch ! .
        /// </summary>
        internal static string CardIsLocked {
            get {
                return ResourceManager.GetString("CardIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mở thẻ (Tháng/Năm:mm/yyyy).
        /// </summary>
        internal static string DateValidFrom {
            get {
                return ResourceManager.GetString("DateValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tính phí.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ ngân hàng nội địa.
        /// </summary>
        internal static string OnlineBankingTitle {
            get {
                return ResourceManager.GetString("OnlineBankingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã OTP.
        /// </summary>
        internal static string OTPCode {
            get {
                return ResourceManager.GetString("OTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin thanh toán.
        /// </summary>
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mở thẻ.
        /// </summary>
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng đăng ký.
        /// </summary>
        internal static string RegistrationMonth {
            get {
                return ResourceManager.GetString("RegistrationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm đăng ký.
        /// </summary>
        internal static string RegistrationYear {
            get {
                return ResourceManager.GetString("RegistrationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không Xác định được ngân hàng thanh toán.
        /// </summary>
        internal static string UnknowBank {
            get {
                return ResourceManager.GetString("UnknowBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên chủ thẻ..
        /// </summary>
        internal static string ValidateAccHolder {
            get {
                return ResourceManager.GetString("ValidateAccHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ thẻ không được nhập các ký tự đặc biệt.
        /// </summary>
        internal static string ValidateAccHolderCharacters {
            get {
                return ResourceManager.GetString("ValidateAccHolderCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn loại xác thực.
        /// </summary>
        internal static string ValidateAccType {
            get {
                return ResourceManager.GetString("ValidateAccType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số thẻ.
        /// </summary>
        internal static string ValidateCardNumber {
            get {
                return ResourceManager.GetString("ValidateCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã khách hàng.
        /// </summary>
        internal static string ValidateCustomCode {
            get {
                return ResourceManager.GetString("ValidateCustomCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được nhập các ký tự đặc biệt.
        /// </summary>
        internal static string ValidateCustomCodeCharacters {
            get {
                return ResourceManager.GetString("ValidateCustomCodeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không vượt quá 30 ký tự.
        /// </summary>
        internal static string ValidateCustomCodeSize {
            get {
                return ResourceManager.GetString("ValidateCustomCodeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu là ký tự số.
        /// </summary>
        internal static string ValidateNumber {
            get {
                return ResourceManager.GetString("ValidateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngày đăng mở thẻ.
        /// </summary>
        internal static string ValidateRegisterDate {
            get {
                return ResourceManager.GetString("ValidateRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mở thẻ không hợp lệ. Ngày mở thẻ có định dạng (MM/YYYY).
        /// </summary>
        internal static string ValidateRegisterDateSize {
            get {
                return ResourceManager.GetString("ValidateRegisterDateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu nhỏ nhất 6 ký tự và nhiều nhất 30 ký tự.
        /// </summary>
        internal static string ValidateSize {
            get {
                return ResourceManager.GetString("ValidateSize", resourceCulture);
            }
        }
    }
}
