//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Response {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Response.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản thanh toán và tài khoản nhận phải khác nhau.
        /// </summary>
        internal static string AccountDuplicate {
            get {
                return ResourceManager.GetString("AccountDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã tồn tại trên hệ thống.
        /// </summary>
        internal static string AccountExisted {
            get {
                return ResourceManager.GetString("AccountExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chưa được kích hoạt. Vui lòng kích hoạt {0}..
        /// </summary>
        internal static string AccountInActive {
            get {
                return ResourceManager.GetString("AccountInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa gắn kết với thẻ ngân hàng.
        /// </summary>
        internal static string AccountNotLinkBank {
            get {
                return ResourceManager.GetString("AccountNotLinkBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn không thể thực hiện chức năng này.
        /// </summary>
        internal static string AccountNotUseFunction {
            get {
                return ResourceManager.GetString("AccountNotUseFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hoạt động.
        /// </summary>
        internal static string AccountUnActive {
            get {
                return ResourceManager.GetString("AccountUnActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản kích hoạt không tồn tại.
        /// </summary>
        internal static string ActiveAccNotExist {
            get {
                return ResourceManager.GetString("ActiveAccNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kích hoạt không hợp lệ.
        /// </summary>
        internal static string ActiveCodeInvalid {
            get {
                return ResourceManager.GetString("ActiveCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vượt quá hạn mức tiêu trong ngày là .
        /// </summary>
        internal static string AmountPayLimitDay {
            get {
                return ResourceManager.GetString("AmountPayLimitDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vượt quá hạn mức tiêu trong tháng là.
        /// </summary>
        internal static string AmountPayLimitMonth {
            get {
                return ResourceManager.GetString("AmountPayLimitMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán vượt quá hạn mức giao dịch là .
        /// </summary>
        internal static string AmountPayMaxLimit {
            get {
                return ResourceManager.GetString("AmountPayMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán không hợp lệ.
        /// </summary>
        internal static string AmountPaymentInvalid {
            get {
                return ResourceManager.GetString("AmountPaymentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền thanh toán nhỏ hơn hạn mức yêu cầu là .
        /// </summary>
        internal static string AmountPayMinLitmit {
            get {
                return ResourceManager.GetString("AmountPayMinLitmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản khách hàng không đủ điều kiện giao dịch.
        /// </summary>
        internal static string BankAccountNotEligible {
            get {
                return ResourceManager.GetString("BankAccountNotEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng không tồn tại.
        /// </summary>
        internal static string BankNotExist {
            get {
                return ResourceManager.GetString("BankNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng thanh toán không hợp lệ.
        /// </summary>
        internal static string BankPaymentInvalid {
            get {
                return ResourceManager.GetString("BankPaymentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị khóa 15 phút do đăng nhập sai 5 lần. Hãy thử lại sau 15 phút..
        /// </summary>
        internal static string BlockByLoginFail {
            get {
                return ResourceManager.GetString("BlockByLoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        internal static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kiểm tra đã hết hạn. Vui lòng đổi mã kiểm tra.
        /// </summary>
        internal static string CaptchaExpires {
            get {
                return ResourceManager.GetString("CaptchaExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kiểm tra không hợp lệ.
        /// </summary>
        internal static string CaptchaInvalid {
            get {
                return ResourceManager.GetString("CaptchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khởi tạo đơn hàng thất bại.
        /// </summary>
        internal static string CreateOrderFail {
            get {
                return ResourceManager.GetString("CreateOrderFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng hủy đơn hàng, Bank thông báo hủy đơn hàng.
        /// </summary>
        internal static string CustomerOrderCancel {
            get {
                return ResourceManager.GetString("CustomerOrderCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bạn cung cấp không hợp lệ. .
        /// </summary>
        internal static string DataNotValid {
            get {
                return ResourceManager.GetString("DataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng để đăng ký trên hệ thống.
        /// </summary>
        internal static string EmailExisted {
            get {
                return ResourceManager.GetString("EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng xác thực email.
        /// </summary>
        internal static string EmailNotVerify {
            get {
                return ResourceManager.GetString("EmailNotVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không hợp lệ.
        /// </summary>
        internal static string FullNameInvalid {
            get {
                return ResourceManager.GetString("FullNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã kích hoạt.
        /// </summary>
        internal static string InputActiveCode {
            get {
                return ResourceManager.GetString("InputActiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ đăng ký kinh doanh.
        /// </summary>
        internal static string InputAddressBussiness {
            get {
                return ResourceManager.GetString("InputAddressBussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên doanh nghiệp.
        /// </summary>
        internal static string InputBussinessName {
            get {
                return ResourceManager.GetString("InputBussinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số giấy ĐKKD.
        /// </summary>
        internal static string InputBussinessRegister {
            get {
                return ResourceManager.GetString("InputBussinessRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã kiểm tra.
        /// </summary>
        internal static string InputCaptcha {
            get {
                return ResourceManager.GetString("InputCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ email.
        /// </summary>
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ và tên.
        /// </summary>
        internal static string InputFullName {
            get {
                return ResourceManager.GetString("InputFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ trụ sở chính.
        /// </summary>
        internal static string InputHeadOffice {
            get {
                return ResourceManager.GetString("InputHeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập điện thoại liên hệ.
        /// </summary>
        internal static string InputMobileContact {
            get {
                return ResourceManager.GetString("InputMobileContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số CMTND, Hộ chiếu.
        /// </summary>
        internal static string InputPassport {
            get {
                return ResourceManager.GetString("InputPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu.
        /// </summary>
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã xác thực.
        /// </summary>
        internal static string InputSecureCode {
            get {
                return ResourceManager.GetString("InputSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã bảo mật cho thiết bị mới.
        /// </summary>
        internal static string InputSecureCodeNewDevice {
            get {
                return ResourceManager.GetString("InputSecureCodeNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã số thuế.
        /// </summary>
        internal static string InputTaxCode {
            get {
                return ResourceManager.GetString("InputTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tài khoản.
        /// </summary>
        internal static string InputUserName {
            get {
                return ResourceManager.GetString("InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập ngay.
        /// </summary>
        internal static string LoginNow {
            get {
                return ResourceManager.GetString("LoginNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng nhập thành công..
        /// </summary>
        internal static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi ngày chỉ nhận tối đa 3 lần ODP SMS.
        /// </summary>
        internal static string Max3ODP {
            get {
                return ResourceManager.GetString("Max3ODP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không đủ số dư để thực hiện giao dịch.
        /// </summary>
        internal static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại VTC Pay không hỗ trợ đăng ký nhanh cho các số điện thoại không thuộc các mạng Viettel, Vinaphone, Mobifone, Vietnamobile. Để tiếp tục đăng ký vui lòng click &lt;a href=\&quot;https://pay.vtc.vn/#dang-ky-440\&quot; target=\&quot;_blank\&quot; &gt;tại đây&lt;/a&gt;.
        /// </summary>
        internal static string NoteTelcoFastReg {
            get {
                return ResourceManager.GetString("NoteTelcoFastReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư trong tài khoản không đủ để thực hiện giao dịch!&lt;br/&gt;Vui lòng thanh toán bằng tài khoản &lt;a href=\&quot;{0}\&quot; &gt;&lt;b&gt;Ngân hàng/Ví điện tử&lt;/b&gt;&lt;/a&gt; hoặc &lt;a href=\&quot;{1}\&quot;&gt;&lt;b&gt;Nạp thêm tiền&lt;/b&gt;&lt;/a&gt; vào tài khoản.&lt;br/&gt;&lt;a href=\&quot;{2}\&quot; &gt;&lt;b&gt;Click vào đây&lt;/b&gt;&lt;/a&gt; để quay trở lại trang chủ.
        /// </summary>
        internal static string NotMoneyGotoGate {
            get {
                return ResourceManager.GetString("NotMoneyGotoGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào email {0} và số điện thoại của bạn..
        /// </summary>
        internal static string OdpEmaiSent {
            get {
                return ResourceManager.GetString("OdpEmaiSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi lần click nhận lại ODP SMS phải cách nhau 30s.
        /// </summary>
        internal static string ODPOther30s {
            get {
                return ResourceManager.GetString("ODPOther30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhận mã ODP quá 3 lần.
        /// </summary>
        internal static string OdpOver3 {
            get {
                return ResourceManager.GetString("OdpOver3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào email.
        /// </summary>
        internal static string ODPResentMail {
            get {
                return ResourceManager.GetString("ODPResentMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào số điện thoại của bạn.
        /// </summary>
        internal static string ODPResentPhone {
            get {
                return ResourceManager.GetString("ODPResentPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODP đang được gửi, bạn vui lòng chờ.
        /// </summary>
        internal static string OdpSending {
            get {
                return ResourceManager.GetString("OdpSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi lại vào số điện thoại của bạn. Vui lòng kiểm tra lại..
        /// </summary>
        internal static string OdpSent {
            get {
                return ResourceManager.GetString("OdpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực ODP đã được gửi vào email {0} và số điện thoại của bạn.
        /// </summary>
        internal static string ODPsentMailAndPhone {
            get {
                return ResourceManager.GetString("ODPsentMailAndPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng thanh toán tại ngân hàng thất bại.
        /// </summary>
        internal static string OrderBankFail {
            get {
                return ResourceManager.GetString("OrderBankFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng không hợp lệ.
        /// </summary>
        internal static string OrderInvalid {
            get {
                return ResourceManager.GetString("OrderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP đã hết hạn, bạn vui lòng nhập lại theo vị trí mới.
        /// </summary>
        internal static string OtpExpired {
            get {
                return ResourceManager.GetString("OtpExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh thư không hợp lệ. Độ dài từ 9-12 ký tự.
        /// </summary>
        internal static string PassportPolicy {
            get {
                return ResourceManager.GetString("PassportPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tài khoản của bạn đã lâu không được thay đổi, bạn cần phải đổi mật khẩu mới để tiếp tục sử dụng dịch vụ. Trân trọng cảm ơn.
        /// </summary>
        internal static string PasswordOldNeedChange {
            get {
                return ResourceManager.GetString("PasswordOldNeedChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu từ 8-18 ký tự bao gồm cả chữ hoa, chữ thường và chữ số.
        /// </summary>
        internal static string PasswordPolicy {
            get {
                return ResourceManager.GetString("PasswordPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch quá thời gian thanh toán. Vui lòng thực hiện lại.
        /// </summary>
        internal static string PaymentExpired {
            get {
                return ResourceManager.GetString("PaymentExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ.
        /// </summary>
        internal static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần nhập tối thiểu 10,000 VNĐ.
        /// </summary>
        internal static string RechargeMinInvalid {
            get {
                return ResourceManager.GetString("RechargeMinInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận tiền không hợp lệ hoặc đang bị khóa.
        /// </summary>
        internal static string RecieverAccountInvalid {
            get {
                return ResourceManager.GetString("RecieverAccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng ký thành công.
        /// </summary>
        internal static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu không hợp lệ .
        /// </summary>
        internal static string RequestInvalid {
            get {
                return ResourceManager.GetString("RequestInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu nhập lại không đúng.
        /// </summary>
        internal static string RetypePassInvalid {
            get {
                return ResourceManager.GetString("RetypePassInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lại MK.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng ứng dụng VTC Pay hoặc ứng dụng bất kỳ  &lt;br&gt;có tính năng quét mã QR Code để thanh toán.
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật không hợp lệ.
        /// </summary>
        internal static string SecureCodeInvalid {
            get {
                return ResourceManager.GetString("SecureCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã bảo mật nhập sai quá số lần quy định. Chúng tôi sẽ khóa chức năng giao dịch trong 5 phút.
        /// </summary>
        internal static string SecureCodeWrongManyTime {
            get {
                return ResourceManager.GetString("SecureCodeWrongManyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn tình thành phố.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn quận huyện.
        /// </summary>
        internal static string SelectDistrict {
            get {
                return ResourceManager.GetString("SelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mã thẻ không thành công.
        /// </summary>
        internal static string SentCardCodeFail {
            get {
                return ResourceManager.GetString("SentCardCodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi mã bảo mật thất bại. Vui lòng thử lại !.
        /// </summary>
        internal static string SentSecureCodeFail {
            get {
                return ResourceManager.GetString("SentSecureCodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ truy cập không hợp lệ.
        /// </summary>
        internal static string ServiceInvalid {
            get {
                return ResourceManager.GetString("ServiceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đang bận, vui long quay lại sau.
        /// </summary>
        internal static string SystemBusy {
            get {
                return ResourceManager.GetString("SystemBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi giao dịch tại hệ thống ngân hàng.
        /// </summary>
        internal static string TransactionBankFail {
            get {
                return ResourceManager.GetString("TransactionBankFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thanh toán thất bại.
        /// </summary>
        internal static string TransactionFail {
            get {
                return ResourceManager.GetString("TransactionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch không hợp lệ.
        /// </summary>
        internal static string TransactionInvalid {
            get {
                return ResourceManager.GetString("TransactionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch tại ngân hàng đã thành công, nhưng số tiền thanh toán từ Bank trả về không khớp với dữ liệu tại hệ thống VTC.
        /// </summary>
        internal static string TransactionNotMatch {
            get {
                return ResourceManager.GetString("TransactionNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đã bị từ chối !.
        /// </summary>
        internal static string TransactionReject {
            get {
                return ResourceManager.GetString("TransactionReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đang được xử lý.
        /// </summary>
        internal static string TransactionReview {
            get {
                return ResourceManager.GetString("TransactionReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã giao dịch thành công..
        /// </summary>
        internal static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đủ thông tin trả về từ bank để có  thể xác định được trạng thái của giao dịch.
        /// </summary>
        internal static string TransactionUnknow {
            get {
                return ResourceManager.GetString("TransactionUnknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi giao dịch tại hệ thống VTCPay.
        /// </summary>
        internal static string TransactionVTCFail {
            get {
                return ResourceManager.GetString("TransactionVTCFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng đăng nhập hệ thống để sử dụng dịch vụ.
        /// </summary>
        internal static string Unlogin {
            get {
                return ResourceManager.GetString("Unlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng nhập thì redirect sang cổng thanh toán.
        /// </summary>
        internal static string UnloginGotoGate {
            get {
                return ResourceManager.GetString("UnloginGotoGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không hợp lệ.
        /// </summary>
        internal static string UserNameInvalid {
            get {
                return ResourceManager.GetString("UserNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản không hợp lệ, độ dài từ 9 - 11.
        /// </summary>
        internal static string UsernameInvalidLength {
            get {
                return ResourceManager.GetString("UsernameInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không hợp lệ..
        /// </summary>
        internal static string UserOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có sử dụng dịch vụ bảo mật ODP, OTP.
        /// </summary>
        internal static string UsingSecurity {
            get {
                return ResourceManager.GetString("UsingSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không hợp lệ.
        /// </summary>
        internal static string VerifyCodeInvalid {
            get {
                return ResourceManager.GetString("VerifyCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai chữ ký.
        /// </summary>
        internal static string WrongSignal {
            get {
                return ResourceManager.GetString("WrongSignal", resourceCulture);
            }
        }
    }
}
